# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    
    obj = bld.create_ns3_program('firefly_dynamic_clustering-example', 
    							['core', 'wifi', 'applications','tools', 'internet', 'firefly_dynamic_clustering'])
    obj.source = 'firefly_dynamic_clustering-example.cc'